config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  # ユーザー関連のルート
  resources :users, only: [:show] do
    collection do
      get 'search' # 検索機能用のルート
    end
  end

  resources :profiles, only: [:new, :create, :edit, :update] do
    collection do
      get 'ranking' # ランキングページのルート
    end
  end

  resources :profiles, only: [] do
    resources :likes, only: [:create]
  end

  # プロフィール関連のルート
  resources :profiles, only: [:new, :create, :edit, :update]

  # 固定ページのルート
  get "/help", to: "pages#help"

  # ルート設定: mypage をホームとして設定
  root "pages#mypage"

  #フォロー機能
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]

  has_one :profile, dependent: :destroy
  has_many :likes, dependent: :destroy

  # 条件付きバリデーション: サインアップ時はスキップ
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 50 }, unless: :new_record?

  # フォロー機能の関連付け
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  # OAuthログイン時の処理
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.username = auth.info.name || "user_#{SecureRandom.hex(4)}"
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # callback for google
  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    # 'request.env["omniauth.auth"]' には Google アカウントから取得したデータが含まれています
    @user = User.from_omniauth(request.env["omniauth.auth"])
    
    if @user.persisted?
      # sign_in_and_redirect をカスタムリダイレクトに変更
      sign_in @user, event: :authentication
      redirect_to user_path(@user)  # /users/:id にリダイレクト
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    begin
      @user = User.find(params[:id])
      @profile = @user.profile # 対応するプロフィールを取得
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path, alert: "ユーザーが見つかりませんでした。"
    end
  end

  def search
    @query = params[:query] # 検索キーワードを取得
    if @query.present?
      # profilesテーブルでusernameを検索
      @profiles = Profile.where("username LIKE ?", "%#{@query}%")
      @users = @profiles.map(&:user) # 関連するユーザーを取得
    else
      @users = []
    end
  end  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/search.html.erb
<h1>検索結果</h1>

<% if @users.any? %>
  <ul>
    <% @users.each do |user| %>
      <li>
        <%= link_to user.profile.username, user_path(user) %> <!-- ユーザーネームをリンクに -->
      </li>
    <% end %>
  </ul>
<% else %>
  <p>該当するユーザーが見つかりませんでした。</p>
<% end %>

<%= link_to "マイページに戻る", user_path(current_user) %>

app/views/users/show.html.erb
<div class="user-page-header">
  <h1>
    <% if @user.profile.present? %>
      <%= @user.profile.username %>のプロフィール
    <% else %>
      プロフィールが未登録です
    <% end %>
  </h1>

  <% if current_user != @user && @user.profile.present? %>
    <% if current_user.following.include?(@user) %>
      <%= button_to "フォロー解除", relationship_path(@user), method: :delete, class: "btn btn-danger btn-sm" %>
    <% else %>
      <%= button_to "このユーザーをフォローする", relationships_path(followed_id: @user.id), method: :post, class: "btn btn-primary btn-sm" %>
    <% end %>
  <% end %>
</div>

<div class="search-form-container">
  <div class="search-form">
    <%= form_with url: search_users_path, method: :get, local: true do |f| %>
      <div class="form-group">
        <%= f.text_field :query, class: "form-control", placeholder: "ユーザーを検索" %>
      </div>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<div class="profile-details">
  <% if @user.profile.present? %>
    <div>
      <%# 「今やっていること」のセクション %>
      <p><strong>今やっていること:</strong> <%= @user.profile.doing.presence || "未登録" %></p>
      <%= form_with url: profile_likes_path(@user.profile), method: :post, local: true, class: "like-form" do %>
        <%= hidden_field_tag :field, "doing" %>
        <button type="submit" class="like-button">☆</button>
        <span class="like-count"><%= @user.profile.likes.where(field: "doing").count %></span>
      <% end %>

      <%# 「趣味」のセクション %>
      <p><strong>趣味:</strong> <%= @user.profile.hobbies.presence || "未登録" %></p>
      <%= form_with url: profile_likes_path(@user.profile), method: :post, local: true, class: "like-form" do %>
        <%= hidden_field_tag :field, "hobbies" %>
        <button type="submit" class="like-button">☆</button>
        <span class="like-count"><%= @user.profile.likes.where(field: "hobbies").count %></span>
      <% end %>

      <%# 「ひとこと」のセクション %>
      <p><strong>ひとこと:</strong> <%= @user.profile.comment.presence || "未登録" %></p>
      <%= form_with url: profile_likes_path(@user.profile), method: :post, local: true, class: "like-form" do %>
        <%= hidden_field_tag :field, "comment" %>
        <button type="submit" class="like-button">☆</button>
        <span class="like-count"><%= @user.profile.likes.where(field: "comment").count %></span>
      <% end %>
    </div>

    <%# ログイン中のユーザーが自分のプロフィールを見ている場合のみ「プロフィールを編集する」ボタンを表示 %>
    <% if current_user == @user %>
      <%= link_to "プロフィールを編集する", edit_profile_path(@user.profile), class: "btn btn-primary mt-3" %>
    <% end %>
  <% else %>
    <p>プロフィールが未登録です。</p>
    <% if current_user == @user %>
      <%= link_to "プロフィールを登録する", new_profile_path, class: "btn btn-primary mt-3" %>
    <% end %>
  <% end %>
</div>

<%# 自分のページではない場合のみ「戻る」リンクを表示 %>
<% if current_user != @user %>
  <%= link_to "戻る", user_path(current_user), class: "btn btn-primary mt-3" %>
<% end %>

<% if current_user == @user %>
  <h2>フォロー中のユーザー</h2>
  <% if current_user.following.any? %>
    <ul>
      <% current_user.following.each do |user| %>
        <li>
          <%= link_to user.profile&.username || "名前未設定", user_path(user) %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>フォローしているユーザーはいません。</p>
  <% end %>
<% end %>